### ISSUE TITLE
Consider dropping `timestring`

### ISSUE THREAD

**Issue by SimonSchick** [evanshortiss/express-expeditious#11]
I understand that using human readable strings is nice, but in real life are not really that much better than their millisecond counterpart.
You also can drop 1 more dependency.

**Comment by evanshortiss** [comment]
@SimonSchick thanks for the suggestion. It's something I was torn on adding initially vs. just letting people use it themselves if needed. 

Is this affecting your usage of the module? Or can we close this?

**Comment by evanshortiss** [comment]
Ha, it's definitely a subjective issue. I personally like to see `1 hour` as opposed to `60 * 60 * 1000`, but there's definitely no _need_ for it to be in core as you point out. It's also nice when reading them as environment variables, but again, can be done without being in core 👍 

Could do a release to reduce the bloat, would just need to bump a major version...
