### ISSUE TITLE
POST request is not getting cached

### ISSUE THREAD

**Issue by Nodics** [evanshortiss/express-expeditious#13]
Hi,

I am using this to cache my API request at express middleware level with "expeditious-engine-memory" engine.

This working fine for 'GET' request, but not working for 'POST'. I am using 'POST' request for passing a query to fetch result.

Please help me

**Comment by evanshortiss** [comment]
Hi @Nodics, per the [docs here](https://github.com/evanshortiss/express-expeditious#default) only GET requests with HTTP 200 responses are cached by default. If you'd like to cache GET and POST then you can implement a modified version of the _shouldCache_ example [here](https://github.com/evanshortiss/express-expeditious#custom)

**Comment by evanshortiss** [comment]
If have issues with this please reopen the issue.
