### ISSUE TITLE
How to use with compression middleware

### ISSUE THREAD

**Issue by ryanto** [evanshortiss/express-expeditious#17]
In our express middleware stack we also use the compression middleware (https://github.com/expressjs/compression). If compression is turned on while using express-expeditious there's a bug that happens.

The first time a client visits the site there is a cache miss, the page is rendered, and the compressed result is put into the cache. The browser correctly renders the page.

The second time a client visits the site there is a cache hit, but the cache hit ends up being a 10 byte invalid binary payload. An error is shown in the browser.

Disabling compression for cache hits still results in this bug. `detect_buffers` has no effect either. I have a feeling it's how the compressed data is cached.

I'm more than happy to put together a demo app that shows this bug. Just let me know!

**Comment by evanshortiss** [comment]
Hi @ryanto IIRC I've had this issue before. I think you simply need to swap the middleware order so `compression` happens after caching.

This example seems to work as expected for me:

```js
const app = require('express')()

app.use(require('express-expeditious')({
    namespace: 'expresscache',
    defaultTtl: '1 minute'
}))

app.use(require('compression')())

app.get('/', (req, res) => {
    res.json({
        hello: 'world'
    })
})

app.listen(3030)
```

Let me know if this works. If not I'll need that demo 😄

**Comment by evanshortiss** [comment]
I'm just thinking now that my solution will result in a non-compressed response from cache hits, right? That's not ideal! Maybe this needs more investigation.

**Comment by ryanto** [comment]
Hey thanks for the reply! I'll set up a demo app this week to use as a playground & testbed for these scenarios.

**Comment by cyrilchapon** [comment]
+1 so much

**Comment by evanshortiss** [comment]
Excellent summary, I like it.

> This implies middleware ordering, but the point is Express middlware ordering strategy is about requests and not responses.

I just did some debugging here (sorry it took so long to get around to), but it looks like an issue with the parsing of the http response (https://github.com/evanshortiss/express-expeditious/blob/master/lib/middleware.js#L195)[here]. Hopefully a patch to the parser might address this so we don't need to mess with middleware at all 😄 

@ryanto @cyrilchapon, you can see the details of the debugging in this issue - https://github.com/creationix/http-parser-js/issues/54

**Comment by evanshortiss** [comment]
I should add that the manner in which I was accumulating the Buffer was also bugged, so it's a two fold issue. I have found the fix for the Buffer issue on my end, just digging into what appears to be a bug-like behaviour with "transfer-encoding: chunked" in the `http-parser-js`

**Comment by cyrilchapon** [comment]
@evanshortiss, some great reporting here.

I'm so damn lost with that HTTP parser stuff, but I'm hard following this.

If that get's fixed, I might give a try to integrate it inside my node.js based reverse proxy 😁

**Comment by evanshortiss** [comment]
@cyrilchapon @ryanto can you try using testing branch in this PR https://github.com/evanshortiss/express-expeditious/pull/19/files? I believe it fixes the issues we've been seeing. It has some changes though in terms of the stored object being a buffer instead of string and the module no longer uses the `http-parser-js` since it's not necessary really! 😄

**Comment by ryanto** [comment]
Hey Evan - I just tried out your branch and everything is working great!

**Comment by cyrilchapon** [comment]
Good to hear. I might not have a chance in next week but I'll do try during this month ☺️

Thanks again ! 💋

**Comment by evanshortiss** [comment]
Awesome, will land it in the next 2 days.
