### ISSUE TITLE
Mismatch between required/optional params

### ISSUE THREAD

**Issue by pkoniu** [evanshortiss/express-expeditious#18]
According to this [section](https://github.com/evanshortiss/express-expeditious#moduleopts) in readme the following should be possible:
``` javascript
const middlewareBuilder = require('express-expeditious');
const expeditious = require('expeditious');

const settings = {
    namespace: 'test',
    defaultTtl: 60000,
    objectMode: true
};
const expeditiousInstance = expeditious(settings);
const middleware = middlewareBuilder({ expeditious: expeditiousInstance });
```

But last line throws an AssertionError: `opts.defaultTtl is required and should be a positive Number`.

**Comment by evanshortiss** [comment]
@pkoniu I think what you really might want to do is just:

```js
const middleware = require('express-expeditious')({
    namespace: 'test',
    defaultTtl: 60000,
})
```

**Comment by pkoniu** [comment]
Didn't find where the bug is but changed the whole logic for creating those cache instances. Thus I think we can close it for now. Sorry for any confusion I may have created. Have a good day :)

**Comment by evanshortiss** [comment]
👍 good to hear
