### ISSUE TITLE
Cacheable based on backend response?

### ISSUE THREAD

**Issue by ryanto** [evanshortiss/express-expeditious#21]
Would there be interest in an option to check a response for cachablility before writing it to the cache?

This sort of already happens by checking the response status code against `getCacheExpiry` before committing it. https://github.com/evanshortiss/express-expeditious/blob/master/lib/middleware.js#L136

It would be nice if other information in the response could be used to determine if a response is cacheable, like `Cache-Control` or other headers provided by the backend.

Something like `withResponseCondition(function)`

I'm happy to get started on this if there's interest.

**Comment by evanshortiss** [comment]
@ryanto yeah, I think this could be useful. Right now `shouldCache` is run on the incoming request, but if I understand correctly you're asking if something should also be run on the response? I think that's a good idea 👍

**Comment by ryanto** [comment]
Yup exactly. I'll start a PR in the next few weeks.

**Comment by patrickmichalina** [comment]
Is this still getting built out? Would be nice to have the backend act like a browser and only cache content that is supposed to be. At least implement a subset of Cache-Control, Expires, etc.

**Comment by evanshortiss** [comment]
@ryanto I'll close this for now. Feel free to come back to it anytime and we can discuss or merge a PR.
