### ISSUE TITLE
Issues when we run the load test

### ISSUE THREAD

**Issue by maheshyamsani** [evanshortiss/express-expeditious#28]
Hi, 
I was trying to do a stress testing my application which use express-expeditious by Defaulting to expeditious-engine-memory

When I was running our tets with -n 1000 and -c 100 I can see the below error, can you please advice in resolving the issue

/home/nodejs/app/node_modules/express-expeditious/lib/middleware.js:254
_write = res.socket.write.bind(res.socket)
^
TypeError: Cannot read property 'write' of null
at processRequest (/home/nodejs/app/node_modules/express-expeditious/lib/middleware.js:254:29)
at onCacheReturned (/home/nodejs/app/node_modules/express-expeditious/lib/middleware.js:89:9)
at /home/nodejs/app/node_modules/safejson/src/index.js:55:14
at deferred (/home/nodejs/app/node_modules/safejson/src/index.js:15:5)
at Object.exports.parse (/home/nodejs/app/node_modules/safejson/src/index.js:51:3)
at onGetCallComplete (/home/nodejs/app/node_modules/expeditious/lib/handlers.js:33:18)
at Immediate._onImmediate (/home/nodejs/app/node_modules/expeditious-engine-memory/expeditious-memory-engine.js:50:9)
at runCallback (timers.js:810:20)
at tryOnImmediate (timers.js:768:5)
at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by maheshyamsani** [comment]
and it is crashing whole my application by killing it

**Comment by evanshortiss** [comment]
@maheshyamsani, few questions:

* is this running locally or your machine?
* what node.js version are you using?
* can you provide a small sample application/code that recreates the error?

**Comment by evanshortiss** [comment]
When you can, patch try this branch by updating your package.json like this and doing `npm install`:

```json
{
  "dependencies": {
    "express-expeditious": "evanshortiss/express-expeditious#socket-write-patch"
  }
}
```

**Comment by maheshyamsani** [comment]
> @maheshyamsani, few questions:
> 
> * is this running locally on your machine or somewhere else?
> * what node.js version are you using?
> * can you provide a small sample application/code that recreates the error?

Was running it on one of my aws instances behind the load balancers, and I can see same error across all instances , when I run the load test following goad approach (https://goad.io/)

The version I am using is 8.0
It is reproducable when I gace -n 1000 and -c 100 with any simple code

**Comment by maheshyamsani** [comment]
> "express-expeditious": "evanshortiss/express-expeditious#socket-write-patch"

I was getting the below issue when I was trying to build 

`npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/evanshortiss/express-expeditious.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-23T06_56_09_342Z-debug.log`

**Comment by evanshortiss** [comment]
@maheshyamsani hmm, try run this instead, it worked for me: `npm i evanshortiss/express-expeditious -S`

My `package.json` then contained:

```
"dependencies": {
  "express-expeditious": "github:evanshortiss/express-expeditious"
}
```

**Comment by evanshortiss** [comment]
Try this instead `npm i evanshortiss/express-expeditious#socket-write-patch -S`. It worked for me on npm 6.4.1

**Comment by evanshortiss** [comment]
@maheshyamsani thanks for the information. OK, so it sounds like it only happens when the application is behind a load balancer or proxy and under load? I'm guessing it has something to do at the socket/network level and that patch *might* do the trick. If not, then I'd need to recreate and test.

**Comment by evanshortiss** [comment]
Oh, and when testing could you enable logging by setting the DEBUG environment variable like so before running your app `export DEBUG=express-expeditious`

**Comment by evanshortiss** [comment]
@maheshyamsani any update on this?

**Comment by maheshyamsani** [comment]
> @maheshyamsani any update on this?

Sorry and thanks for fixing it , I yet to test it . for now I was using the standard redis client to overcome the issue but will let you know the results with your change.

**Comment by evanshortiss** [comment]
@maheshyamsani thanks, would be good to know since I can't create it locally.

**Comment by evanshortiss** [comment]
Haven't recreated this using the latest release on local or when running behind NGINX on a server. Considering resolved unless someone reports it again.
