### ISSUE TITLE
Cancelled requests result in corrupt cache entry

### ISSUE THREAD

**Issue by richardscarrott** [evanshortiss/express-expeditious#54]
We've just gone into production w/ this and found we were getting cache entries with no headers or data e.g.

```
{"headers":"","data":{"type":"Buffer","data":[]}}
```

After a bit of investigation we were able to reproduce this cache entry by cancelling a request before it completes. i.e. In Chrome make the request then hit the stop button before it responds (I found it easier to reproduce by forcing a long timeout before sending back any data).

In the real world this is probably happening because our initial render is too slow so people hit back or close the tab.

I'll try to dig into the code of express-expeditious when I get a chance but wanted to log this issue right away in case you know why this might be happening?

**Comment by evanshortiss** [comment]
@richardscarrott nice find, and sorry about that!

My initial thought is that it should have been caught by the [code here](https://github.com/evanshortiss/express-expeditious/blob/master/lib/middleware.js#L220-L227), but it seems like the socket closing isn't producing an error in `on-finished`. Will need to debug it though.

**Comment by richardscarrott** [comment]
I'm not massively familiar w/ node request / response events in all honesty and frustratingly I see different results depending which version of Node I'm running:

```js
const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
    console.log('__________REQUEST__________')
    // request
    req.on('abort', () => {
        console.log('request: abort');
    })
    req.on('connect', () => {
        console.log('request: connect');
    })
    req.on('continue', () => {
        console.log('request: continue');
    })
    req.on('information', () => {
        console.log('request: information');
    })
    req.on('response', () => {
        console.log('request: response');
    })
    req.on('socket', () => {
        console.log('request: socket');
    })
    req.on('timeout', () => {
        console.log('request: timeout');
    })
    req.on('upgrade', () => {
        console.log('request: upgrade');
    })

    // response
    res.on('close', () => {
        console.log('response: close');
    })
    res.on('finish', () => {
        console.log('response: finish');
    })

    setTimeout(() => {
        res.statusCode = 200;
        res.setHeader('Content-Type', 'text/plain');
        res.end('Hello World\n');
    }, 2000)
});

server.listen(port, hostname, () => {
    console.log(`Server running at http://${hostname}:${port}/`);
});
```

> NOTE: None of the request events run...not sure why?

|           | Node 8.11.3          | Node 10.5.0, Node 11.15.0 and Node 12.7.0 |
|-----------|----------------------|-------------------------------------------|
| 200       | ['response: finish'] | ['response: finish', 'response: close']   |
| Cancelled | ['response: close']  | ['response: close']                       |

The node docs used to say the close event "Indicates that the underlying connection was terminated before response.end() was called or able to flush." but 11+ merely says "Indicates that the underlying connection was terminated." so I guess the functionality was changed in v10 and there's a mistake in the v10 docs.

...anyway that turns out to be a bit of a tangent as I think this would fix it because `on-finished` does not pass an `err` if the response is closed before calling `end`.

``` js
// nit: This handler is called `onRequestFinished` however I think it's actually attached to the `res` object?
function onRequestFinished(err) {
    // Only cache if `res.finished` in case response was closed before ending.
    if (err || !res.finished) {
        log(
            'request error. not parsing response for cache - %j',
            err
        )
        cacheLocks.removeLock(cacheKey)
    } else {
        log('request finished, parsing response for cache')

        const bodyBeginIdx = buf.indexOf('\r\n\r\n')
        const httpData = {
            headers: buf.slice(0, bodyBeginIdx).toString(),
            data: buf.slice(bodyBeginIdx, buf.length)
        }

        onResponseFinished(httpData)
    }
}
`
```

**Comment by richardscarrott** [comment]
@evanshortiss just noticed you've already sent a PR 🤦‍♂ 👍

**Comment by evanshortiss** [comment]
@richardscarrott no worries, and yeah, I went down that same rabbit hole with `on-finished` and the generally misleading Node.js docs! 😂 

I'll release that patch as 5.1.1, then I think I'll release 6.0.0 that drops Node.js 6 support and correctly sets `req.aborted` so I can remove the `aborted` event listener.

> NOTE: None of the request events run...not sure why?

Those events are for a client request object, i.e the one returned by `http.request(options, callback)` AFAIK

**Comment by evanshortiss** [comment]
@richardscarrott closing since this should be all good in 5.1.1
