### ISSUE TITLE
TTL based on request duration

### ISSUE THREAD

**Issue by jloveridge** [evanshortiss/express-expeditious#8]
It would be nice to have an option to set the TTL based on the duration of a request. For instance some analytics based reports are more complex to generate than others and being able to set the cache to 2, 3, or 4 times the duration it takes to generate the non-cache hit would be a welcome addition.

**Comment by evanshortiss** [comment]
@jloveridge just seeing this now.

Do you mean something like the example below?

```
// Will cache the result for 4 times the duration of the request. For example if
// the request takes 15 seconds the cached result will have a TTL of  1 minute
// since 15 * 4 = 60 seconds
app.get('/slow-process', cache.withMultipleOfDuration(4), slowRouteHandler)
```

**Comment by evanshortiss** [comment]
@jloveridge closing this. Please reopen if you'd like to discuss further since it's a nice idea 😄
