### ISSUE TITLE
Vulnerability: Localstore data login

### ISSUE THREAD

**Issue by herhu** [evanshortiss/express-expeditious#84]
Hello mate,

I can jump the Login if I write `user` and `token` with any data in the local store, 
any idea how to improve it?

 anyway am working on that and I will share my solution, but if you have any solution, please feel free to share, can be better than my solution and this can be very nice.

thanks and have a nice day

**Comment by evanshortiss** [comment]
You'll need to share significantly more details than this. 

How does this module relate to "Localstore"? I assume you mean `window.localStorage` in a browser?

This sounds like something specific to your application. Feel free to reopen the issue if you disagree and can provide a full working example of the issue.
