### ISSUE TITLE
Downloading dependancies within corporate firewalls.

### ISSUE THREAD

**Issue by prabuddha82** [evanshortiss/express-expeditious#9]
I started using the library and it goes looking for some dependancies from the GitHub. Some corporate proxies doesn't allow it.  As well I got this error when I try to install my package which again I believe is part of been behind a corporate proxy.

npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/evanshortiss/expeditious.git /root/.npm/_git-remotes/git-https-github-com-evanshortiss-expeditious-git-e997c28c: undefined

**Comment by evanshortiss** [comment]
@prabuddha82 I think I see the problem is [here](https://github.com/evanshortiss/expeditious-engine-memory/blob/master/package.json#L23). Will push a patch now to that module to remove the `git+https` reference.

**Comment by evanshortiss** [comment]
@prabuddha82 just published [this fix](https://github.com/evanshortiss/expeditious-engine-memory/pull/1). If you remove `node_modules` and do an `npm install` I think you'll be good to go, so let me know 😄 

Might also be worth doing `npm cache clean` before `npm install` depending on your version of npm, but `expeditious` should pull in the newly patched `expeditious-engine-memory`

**Comment by evanshortiss** [comment]
@prabuddha82 assuming this is fixed. Please reopen if required.
